export const foodData = [
  {
    name: "Boiled Egg",
    price: 10,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
    image: "/images/egg.png",
    type: "breakfast",
  },
  {
    name: "RAMEN",
    price: 25,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
    image: "/images/ramen.png",
    type: "lunch",
  },
  {
    name: "GRILLED CHICKEN",
    price: 45,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
    image: "/images/chicken.png",
    type: "dinner",
  },
  {
    name: "CAKE",
    price: 18,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
    image: "/images/cake.png",
    type: "breakfast",
  },
  {
    name: "BURGER",
    price: 23,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
    image: "/images/burger.png",
    type: "lunch",
  },
  {
    name: "PANCAKE",
    price: 25,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
    image: "/images/pancake.png",
    type: "dinner",
  },
  {
    name: "Pizza Margherita",
    price: 32,
    text: "Classic Italian pizza with tomato sauce, mozzarella cheese, and fresh basil.",
    image: "/images/burger.png",
    type: "lunch",
  },
  {
    name: "Fruit Salad",
    price: 15,
    text: "A refreshing mix of seasonal fruits.",
    image: "/images/egg.png",
    type: "breakfast",
  },
  {
    name: "Chicken Curry",
    price: 40,
    text: "Flavorful Indian curry with chicken and aromatic spices.",
    image: "/images/ramen.png",
    type: "dinner",
  },
  {
    name: "Coffee",
    price: 8,
    text: "A classic hot beverage to start your day.",
    image: "/images/cake.png",
    type: "breakfast",
  },
  {
    name: "Smoothie",
    price: 12,
    text: "A healthy blend of fruits and yogurt for a refreshing drink.",
    image: "/images/chicken.png",
    type: "snack",
  },
  {
    name: "Sushi",
    price: 38,
    text: "Japanese dish of vinegar rice with various seafood toppings.",
    image: "/images/cake.png",
    type: "lunch",
  },
  {
    name: "Pasta Primavera",
    price: 28,
    text: "Italian pasta dish with seasonal vegetables in a light sauce.",
    image: "/images/pancake.png",
    type: "dinner",
  },
  {
    name: "Ice Cream",
    price: 10,
    text: "A sweet frozen treat in a variety of flavors.",
    image: "/images/burger.png",
    type: "dessert",
  },
  {
    name: "Salad",
    price: 12,
    text: "A mix of greens, vegetables, and optional protein for a healthy meal.",
    image: "/images/egg.png",
    type: "lunch",
  },
  {
    name: "Sandwiches",
    price: 18,
    text: "Bread filled with various meats, cheeses, and vegetables.",
    image: "/images/cake.png",
    type: "lunch",
  },
  {
    name: "Stir Fry",
    price: 35,
    text: "A quick and healthy dish with meat or vegetables stir-fried in a sauce.",
    image: "/images/chicken.png",
    type: "dinner",
  },
  {
    name: "Soup",
    price: 15,
    text: "A warm liquid food made with broth, vegetables, and optional meat.",
    image: "/images/ramen.png",
    type: "lunch",
  },
  {
    name: "Burrito",
    price: 20,
    text: "A large flour tortilla filled with various meats, beans, and vegetables.",
    image: "/images/burger.png",
    type: "lunch",
  },
  {
    name: "Tacos",
    price: 12,
    text: "Small corn tortillas filled with seasoned meat, vegetables, and toppings.",
    image: "/images/cake.png",
    type: "lunch",
  },
  {
    name: "Pasta Carbonari",
    price: 30,
    text: "Italian pasta dish with eggs, cheese, and cured pork.",
    image: "/images/pancake.png",
    type: "dinner",
  },
  {
    name: "Fried Rice",
    price: 22,
    text: "Asian dish of cooked rice stir-fried with vegetables and optional meat.",
    image: "/images/ramen.png",
    type: "dinner",
  },
  {
    name: "Yogurt Parfait",
    price: 14,
    text: "Layered yogurt with granola, fruits, and nuts for a healthy breakfast.",
    image: "/images/chicken.png",
    type: "breakfast",
  },
];
